# Generated by Django 2.2.5 on 2022-08-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220820_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isSuper',
            new_name='superhost',
        ),
    ]
