# Generated by Django 2.2.5 on 2022-09-16 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_bookedday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedday',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
